create table public.form_responses (
  id bigint generated always as identity not null,
  fillout_submission_id text null,
  submitted_at timestamp with time zone null default now(),
  username_raw text null,
  submitter_email text null,
  visa_category text null,
  embassy text null,
  update_type text null,
  i130_priority_date date null,
  i130_rfe boolean null,
  i130_approval date null,
  sent_to_dos date null,
  nvc_welcome_letter date null,
  nvc_fees_paid date null,
  nvc_fees_cleared date null,
  nvc_docs_submitted date null,
  nvc_rfe boolean null,
  dq_date date null,
  interview_letter date null,
  medical date null,
  interview date null,
  interview_expedited boolean null,
  interview_outcome text null,
  resolution_outcome text null,
  visa_approval_date date null,
  passport_delivery_method text null,
  passport_in_hand date null,
  flight date null,
  entry_location text null,
  us_state text null,
  gc_fee_paid date null,
  gc_produced date null,
  gc_received date null,
  ssn_received date null,
  ssa_uscis_intervention boolean null,
  ssa_uscis_issue text null,
  notes text null,
  constraint form_responses_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_form_responses_username on public.form_responses using btree (username_raw) TABLESPACE pg_default;

create index IF not exists idx_form_responses_submitted_at on public.form_responses using btree (submitted_at) TABLESPACE pg_default;
